User:
  type: object
  properties:
    email:
      type: string
    password:
      type: string
Task:
  type: object
  properties:
    title:
      type: string
    description:
      type: string
    dueDate:
      type: string
      format: date-time
    status:
      type: string
      enum:
        - TO_DO
        - IN_PROGRESS
        - COMPLETED
    priority:
      type: string
      enum:
        - LOW
        - MEDIUM
        - HIGH
    userId:
      type: string
